//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicrosoftServices.IdentityManagement.WorkflowActivityLibrary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MicrosoftServices.IdentityManagement.WorkflowActivityLibrary.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse TimeoutDuration value: &apos;{0}&apos;..
        /// </summary>
        internal static string AddDelayActivity_TimeoutDurationValidationError {
            get {
                return ResourceManager.GetString("AddDelayActivity_TimeoutDurationValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource to be created is in conflict with another resource..
        /// </summary>
        internal static string CreateResource_FailedOnConflictError {
            get {
                return ResourceManager.GetString("CreateResource_FailedOnConflictError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get type &apos;{0}&apos; from the current assembly..
        /// </summary>
        internal static string DataAccessService_TypeLoadingFailedError {
            get {
                return ResourceManager.GetString("DataAccessService_TypeLoadingFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The definitions table is null or corrupt.
        /// </summary>
        internal static string DefinitionsConverter_NullOrEmptyDefinitionsTableError {
            get {
                return ResourceManager.GetString("DefinitionsConverter_NullOrEmptyDefinitionsTableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine request actor. The supplied account information is assigned to multiple resources..
        /// </summary>
        internal static string DetermineActor_MultipleActorAccountsError {
            get {
                return ResourceManager.GetString("DetermineActor_MultipleActorAccountsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine request actor. The supplied expression resolved to multiple values..
        /// </summary>
        internal static string DetermineActor_MultipleResolvedActorsError {
            get {
                return ResourceManager.GetString("DetermineActor_MultipleResolvedActorsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine request actor. The supplied account information is not assigned to a resource..
        /// </summary>
        internal static string DetermineActor_NotFoundActorAccountError {
            get {
                return ResourceManager.GetString("DetermineActor_NotFoundActorAccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine request actor. The supplied expression resolved to a null value..
        /// </summary>
        internal static string DetermineActor_NullResolvedActorError {
            get {
                return ResourceManager.GetString("DetermineActor_NullResolvedActorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine request actor. The supplied expression did not resolve to a valid resource ID..
        /// </summary>
        internal static string DetermineActor_UnresolvedActorError {
            get {
                return ResourceManager.GetString("DetermineActor_UnresolvedActorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string ExpressionEvaluator_ExpressionParameterTypeUnsupportedTypeError {
            get {
                return ResourceManager.GetString("ExpressionEvaluator_ExpressionParameterTypeUnsupportedTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string ExpressionEvaluator_ExpressionParameterTypeValidationError {
            get {
                return ResourceManager.GetString("ExpressionEvaluator_ExpressionParameterTypeValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression &apos;{0}&apos; contains an unexpected number of &apos;(&apos; or &apos;)&apos; characters and is invalid..
        /// </summary>
        internal static string ExpressionEvaluator_ExpressionParenthesisValidationError {
            get {
                return ResourceManager.GetString("ExpressionEvaluator_ExpressionParenthesisValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression &apos;{0}&apos; contains an unclosed string and is invalid..
        /// </summary>
        internal static string ExpressionEvaluator_ExpressionQuotesValidationError {
            get {
                return ResourceManager.GetString("ExpressionEvaluator_ExpressionQuotesValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameters for function {0} contain an unexpected number of &apos;(&apos; or &apos;)&apos; characters and are invalid..
        /// </summary>
        internal static string ExpressionEvaluator_FunctionParameterParenthesisValidationError {
            get {
                return ResourceManager.GetString("ExpressionEvaluator_FunctionParameterParenthesisValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameters for function {0} contain an unclosed string and are invalid..
        /// </summary>
        internal static string ExpressionEvaluator_FunctionParameterQuotesValidationError {
            get {
                return ResourceManager.GetString("ExpressionEvaluator_FunctionParameterQuotesValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lookup cache does not contain an entry for &apos;{0}&apos;..
        /// </summary>
        internal static string ExpressionEvaluator_LookupCacheValidationError {
            get {
                return ResourceManager.GetString("ExpressionEvaluator_LookupCacheValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lookup &apos;{0}&apos; contains invalid grammar..
        /// </summary>
        internal static string ExpressionEvaluator_LookupParameterExpressionValidationError {
            get {
                return ResourceManager.GetString("ExpressionEvaluator_LookupParameterExpressionValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lookup &apos;{0}&apos; references an unsupported parameter..
        /// </summary>
        internal static string ExpressionEvaluator_LookupParameterValidationError {
            get {
                return ResourceManager.GetString("ExpressionEvaluator_LookupParameterValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to insert value of type &apos;{0}&apos; into cache for variable &apos;{1}&apos; of type &apos;{2}&apos;..
        /// </summary>
        internal static string ExpressionEvaluator_PublishVariableInsertVariableError {
            get {
                return ResourceManager.GetString("ExpressionEvaluator_PublishVariableInsertVariableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is not a valid string..
        /// </summary>
        internal static string ExpressionEvaluator_StringQuotesValidationError {
            get {
                return ResourceManager.GetString("ExpressionEvaluator_StringQuotesValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the last value expression in the list can leverage the [//UniquenessKey] lookup..
        /// </summary>
        internal static string ExpressionEvaluator_ValueExpressionUniquenessKeyValidationError {
            get {
                return ResourceManager.GetString("ExpressionEvaluator_ValueExpressionUniquenessKeyValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more value expressions are incomplete.
        /// </summary>
        internal static string ExpressionEvaluator_ValueExpressionValidationError {
            get {
                return ResourceManager.GetString("ExpressionEvaluator_ValueExpressionValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The variable cache does not contain an entry for {0}.
        /// </summary>
        internal static string ExpressionEvaluator_VariableCacheValidationError {
            get {
                return ResourceManager.GetString("ExpressionEvaluator_VariableCacheValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function &apos;{0}&apos; is deprecated. Please use &apos;{1}&apos; instead..
        /// </summary>
        internal static string ExpressionFunction_DeprecatedFunctionWarning {
            get {
                return ResourceManager.GetString("ExpressionFunction_DeprecatedFunctionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function &apos;{0}&apos; is improperly formatted or is missing a required parameter. Execution mode: {1}..
        /// </summary>
        internal static string ExpressionFunction_FunctionSyntaxValidationError {
            get {
                return ResourceManager.GetString("ExpressionFunction_FunctionSyntaxValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function &apos;{0}&apos; expects first parameter to be of type &apos;{1}&apos;. It was supplied a &apos;{2}&apos; parameter..
        /// </summary>
        internal static string ExpressionFunction_InvalidFirstFunctionParameterTypeError {
            get {
                return ResourceManager.GetString("ExpressionFunction_InvalidFirstFunctionParameterTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function &apos;{0}&apos; expects first parameter to be of type &apos;{1}&apos; or &apos;{2}&apos;. It was supplied a &apos;{3}&apos; parameter..
        /// </summary>
        internal static string ExpressionFunction_InvalidFirstFunctionParameterTypeError2 {
            get {
                return ResourceManager.GetString("ExpressionFunction_InvalidFirstFunctionParameterTypeError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function &apos;{0}&apos; expects &apos;{1}&apos; parameters. It was supplied &apos;{2}&apos; parameters..
        /// </summary>
        internal static string ExpressionFunction_InvalidFunctionParameterCountError {
            get {
                return ResourceManager.GetString("ExpressionFunction_InvalidFunctionParameterCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function &apos;{0}&apos; expects &apos;{1}&apos; to &apos;{2}&apos; parameters. It was supplied &apos;{3}&apos; parameters..
        /// </summary>
        internal static string ExpressionFunction_InvalidFunctionParameterCountError2 {
            get {
                return ResourceManager.GetString("ExpressionFunction_InvalidFunctionParameterCountError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function &apos;{0}&apos; expects parameter at position {1} in the format &apos;{2}&apos;. It was supplied a value of &apos;{3}&apos;..
        /// </summary>
        internal static string ExpressionFunction_InvalidFunctionParameterError {
            get {
                return ResourceManager.GetString("ExpressionFunction_InvalidFunctionParameterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function &apos;{0}&apos; expects &apos;{1} or more&apos; parameters. It was supplied &apos;{2}&apos; parameters..
        /// </summary>
        internal static string ExpressionFunction_InvalidFunctionParameterMinCountError {
            get {
                return ResourceManager.GetString("ExpressionFunction_InvalidFunctionParameterMinCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function &apos;{0}&apos; expects &apos;{1} to {2}&apos; parameters. It was supplied &apos;{3}&apos; parameters..
        /// </summary>
        internal static string ExpressionFunction_InvalidFunctionParameterMinMaxCountError {
            get {
                return ResourceManager.GetString("ExpressionFunction_InvalidFunctionParameterMinMaxCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function &apos;{0}&apos; expects parameter at position {1} to be of type &apos;{2}&apos;. It was supplied a &apos;{3}&apos; parameter..
        /// </summary>
        internal static string ExpressionFunction_InvalidFunctionParameterTypeError {
            get {
                return ResourceManager.GetString("ExpressionFunction_InvalidFunctionParameterTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request is for an update of the singled-valued attribute &apos;{0}&apos;. Functions ParameterValue must be used instead to read the updated value..
        /// </summary>
        internal static string ExpressionFunction_InvalidParameterValueAddedFunctionUseError {
            get {
                return ResourceManager.GetString("ExpressionFunction_InvalidParameterValueAddedFunctionUseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request is for an update of the multi-valued attribute &apos;{0}&apos;. Functions ParameterValueAdded() or ParameterValueRemoved() must be used instead to read the updated value..
        /// </summary>
        internal static string ExpressionFunction_InvalidParameterValueFunctionUseError {
            get {
                return ResourceManager.GetString("ExpressionFunction_InvalidParameterValueFunctionUseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request is for an update of the singled-valued attribute &apos;{0}&apos;. Functions ParameterValue must be used instead to read the updated value..
        /// </summary>
        internal static string ExpressionFunction_InvalidParameterValueRemovedFunctionUseError {
            get {
                return ResourceManager.GetString("ExpressionFunction_InvalidParameterValueRemovedFunctionUseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function &apos;{0}&apos; expects second parameter to be of type &apos;{1}&apos;. It was supplied a &apos;{2}&apos; parameter..
        /// </summary>
        internal static string ExpressionFunction_InvalidSecondFunctionParameterTypeError {
            get {
                return ResourceManager.GetString("ExpressionFunction_InvalidSecondFunctionParameterTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function &apos;{0}&apos; expects second parameter to be of type &apos;{1}&apos;. It was supplied a &apos;{2}&apos; parameter of value &apos;{3}&apos;..
        /// </summary>
        internal static string ExpressionFunction_InvalidSecondFunctionParameterTypeError2 {
            get {
                return ResourceManager.GetString("ExpressionFunction_InvalidSecondFunctionParameterTypeError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function &apos;{0}&apos; expects second parameter to be of type &apos;{1}&apos; or &apos;{2}&apos;. It was supplied a &apos;{3}&apos; parameter..
        /// </summary>
        internal static string ExpressionFunction_InvalidSecondFunctionParameterTypeError3 {
            get {
                return ResourceManager.GetString("ExpressionFunction_InvalidSecondFunctionParameterTypeError3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function &apos;{0}&apos; expects third parameter to be of type &apos;{1}&apos;. It was supplied a &apos;{2}&apos; parameter..
        /// </summary>
        internal static string ExpressionFunction_InvalidThirdFunctionParameterTypeError {
            get {
                return ResourceManager.GetString("ExpressionFunction_InvalidThirdFunctionParameterTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function &apos;{0}&apos; expects third parameter to be of type &apos;{1}&apos;. It was supplied a &apos;{2}&apos; parameter of value &apos;{3}&apos;..
        /// </summary>
        internal static string ExpressionFunction_InvalidThirdFunctionParameterTypeError2 {
            get {
                return ResourceManager.GetString("ExpressionFunction_InvalidThirdFunctionParameterTypeError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function &apos;{0}&apos; requires the parameter at position &apos;{1}&apos; to be not null..
        /// </summary>
        internal static string ExpressionFunction_NullFunctionParameterError {
            get {
                return ResourceManager.GetString("ExpressionFunction_NullFunctionParameterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use of &apos;//{0}/&apos; lookup in ParametersContain function is deprecated. Use &apos;//{1}/{0}&apos; lookup instead..
        /// </summary>
        internal static string ExpressionFunction_ParametersContainDeprecatedParameterWarning {
            get {
                return ResourceManager.GetString("ExpressionFunction_ParametersContainDeprecatedParameterWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occurred while attempting to &apos;{0}&apos; function &apos;{1}&apos;: &apos;{2}&apos;..
        /// </summary>
        internal static string ExpressionFunction_UnknownFunctionExecutionError {
            get {
                return ResourceManager.GetString("ExpressionFunction_UnknownFunctionExecutionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not recognized as a supported function. Execution mode: &apos;{1}&apos;..
        /// </summary>
        internal static string ExpressionFunction_UnsupportedFunctionError {
            get {
                return ResourceManager.GetString("ExpressionFunction_UnsupportedFunctionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An XPath filter must be supplied for the Find Resources activity..
        /// </summary>
        internal static string FindResources_MissingXPathError {
            get {
                return ResourceManager.GetString("FindResources_MissingXPathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to generate unique value. The activity has exceeded the maximum number ({0}) of unique value generation attempts configured. This is most likely due to a problematic conflict filter or unique value generation logic..
        /// </summary>
        internal static string GenerateUniqueValue_ExceededMaxLoopCountError {
            get {
                return ResourceManager.GetString("GenerateUniqueValue_ExceededMaxLoopCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while attempt to verify the uniqueness of a generated value against the LDAP path &apos;{0}&apos;: &apos;{1}&apos;..
        /// </summary>
        internal static string GenerateUniqueValue_LDAPError {
            get {
                return ResourceManager.GetString("GenerateUniqueValue_LDAPError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GenerateUniqueValue activity attempted {0} of {1} attempts. Consider optimizing your unique value generation logic..
        /// </summary>
        internal static string GenerateUniqueValue_LoopCountWarning {
            get {
                return ResourceManager.GetString("GenerateUniqueValue_LoopCountWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password generator was unable to generate a complex password of length &apos;{0}&apos;. meeting all the complexity criteria (at least one upper case, one lower case, one number and one special char). The current value less complex value will be returned..
        /// </summary>
        internal static string PasswordGenerator_LoopCountWarning {
            get {
                return ResourceManager.GetString("PasswordGenerator_LoopCountWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maxValue must be greater than the minValue..
        /// </summary>
        internal static string PasswordGenerator_MaxValueLessThanMinValueError {
            get {
                return ResourceManager.GetString("PasswordGenerator_MaxValueLessThanMinValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The X.509 encryption certificate with thumbprint &apos;{0}&apos; could not be found..
        /// </summary>
        internal static string ProtectedData_EncryptionCertificateNotFoundError {
            get {
                return ResourceManager.GetString("ProtectedData_EncryptionCertificateNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email template &apos;{0}&apos; is not a GUID value..
        /// </summary>
        internal static string RequestApproval_InvalidEmailTemplateFormatError {
            get {
                return ResourceManager.GetString("RequestApproval_InvalidEmailTemplateFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval complete email template &apos;{1}&apos; not found..
        /// </summary>
        internal static string RequestApproval_MissingApprovalCompleteEmailTemplateError {
            get {
                return ResourceManager.GetString("RequestApproval_MissingApprovalCompleteEmailTemplateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval denied email template &apos;{1}&apos; not found..
        /// </summary>
        internal static string RequestApproval_MissingApprovalDeniedEmailTemplateError {
            get {
                return ResourceManager.GetString("RequestApproval_MissingApprovalDeniedEmailTemplateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending approval email template &apos;{1}&apos; not found..
        /// </summary>
        internal static string RequestApproval_MissingApprovalEmailTemplateError {
            get {
                return ResourceManager.GetString("RequestApproval_MissingApprovalEmailTemplateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval timeout email template &apos;{1}&apos; not found..
        /// </summary>
        internal static string RequestApproval_MissingApprovalTimeoutEmailTemplateError {
            get {
                return ResourceManager.GetString("RequestApproval_MissingApprovalTimeoutEmailTemplateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval escalation email template &apos;{1}&apos; not found..
        /// </summary>
        internal static string RequestApproval_MissingEscalationEmailTemplateError {
            get {
                return ResourceManager.GetString("RequestApproval_MissingEscalationEmailTemplateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one approval complete email templates &apos;{1}&apos; found..
        /// </summary>
        internal static string RequestApproval_MultipleApprovalCompleteEmailTemplatesError {
            get {
                return ResourceManager.GetString("RequestApproval_MultipleApprovalCompleteEmailTemplatesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one approval denied email templates &apos;{1}&apos; found..
        /// </summary>
        internal static string RequestApproval_MultipleApprovalDeniedEmailTemplatesError {
            get {
                return ResourceManager.GetString("RequestApproval_MultipleApprovalDeniedEmailTemplatesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one pending approval email templates &apos;{1}&apos; found..
        /// </summary>
        internal static string RequestApproval_MultipleApprovalEmailTemplatesError {
            get {
                return ResourceManager.GetString("RequestApproval_MultipleApprovalEmailTemplatesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one approval timeout email templates &apos;{1}&apos; found..
        /// </summary>
        internal static string RequestApproval_MultipleApprovalTimeoutEmailTemplatesError {
            get {
                return ResourceManager.GetString("RequestApproval_MultipleApprovalTimeoutEmailTemplatesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one approval escalation email templates &apos;{1}&apos; found..
        /// </summary>
        internal static string RequestApproval_MultipleEscalationEmailTemplatesError {
            get {
                return ResourceManager.GetString("RequestApproval_MultipleEscalationEmailTemplatesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution of the following lookup resulted in multiple values of inconsistent types: &apos;{0}&apos;..
        /// </summary>
        internal static string ResolveLookups_InconsistentTypeError {
            get {
                return ResourceManager.GetString("ResolveLookups_InconsistentTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email template &apos;{0}&apos; not found..
        /// </summary>
        internal static string ReuqestApproval_MissingEmailTemplateError {
            get {
                return ResourceManager.GetString("ReuqestApproval_MissingEmailTemplateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid UserName format {0}. Expected format &quot;Domain\UserName&quot;..
        /// </summary>
        internal static string RunPowerShellActivity_InvalidUserFormat {
            get {
                return ResourceManager.GetString("RunPowerShellActivity_InvalidUserFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerShell script was not found at the location &apos;{0}&apos;..
        /// </summary>
        internal static string RunPowerShellActivity_ScriptNotFoundError {
            get {
                return ResourceManager.GetString("RunPowerShellActivity_ScriptNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PowerShell script returned type: {0} which is inconsistent with the previously returned type: &apos;{1}&apos;..
        /// </summary>
        internal static string RunPowerShellScript_InconsistentScriptReturnTypeError {
            get {
                return ResourceManager.GetString("RunPowerShellScript_InconsistentScriptReturnTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PowerShell script returned a collection of values with inconsistent types..
        /// </summary>
        internal static string RunPowerShellScript_InvalidReturnTypeError {
            get {
                return ResourceManager.GetString("RunPowerShellScript_InvalidReturnTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerShell script execution resulted in {0} error(s):\n.
        /// </summary>
        internal static string RunPowerShellScript_ScriptExecutionFailedError {
            get {
                return ResourceManager.GetString("RunPowerShellScript_ScriptExecutionFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Invoking PowerShell script. Error: &apos;{0}&apos;.
        /// </summary>
        internal static string RunPowerShellScript_ScriptInvocationError {
            get {
                return ResourceManager.GetString("RunPowerShellScript_ScriptInvocationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email template &apos;{0}&apos; is not a GUID value..
        /// </summary>
        internal static string SendEmailNotification_InvalidEmailTemplateFormatError {
            get {
                return ResourceManager.GetString("SendEmailNotification_InvalidEmailTemplateFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email template &apos;{0}&apos; not found..
        /// </summary>
        internal static string SendEmailNotification_MissingEmailTemplateError {
            get {
                return ResourceManager.GetString("SendEmailNotification_MissingEmailTemplateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one email notification templates &apos;{0}&apos; found..
        /// </summary>
        internal static string SendEmailNotification_MultipleEmailTemplatesError {
            get {
                return ResourceManager.GetString("SendEmailNotification_MultipleEmailTemplatesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email template &apos;{0}&apos; is not an XPath filter or a lookup expression or a GUID value..
        /// </summary>
        internal static string SendEmailNotification_ParseEmailTemplateError {
            get {
                return ResourceManager.GetString("SendEmailNotification_ParseEmailTemplateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address &apos;{0}&apos; is not a valid email address..
        /// </summary>
        internal static string SendEmailNotification_ParseRecipientError {
            get {
                return ResourceManager.GetString("SendEmailNotification_ParseRecipientError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A &apos;To&apos; email address must be specified..
        /// </summary>
        internal static string SendEmailNotification_RecipientValidationError {
            get {
                return ResourceManager.GetString("SendEmailNotification_RecipientValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No &apos;To&apos; recipients found. Search filter or lookup expression specified: &apos;{0}&apos;..
        /// </summary>
        internal static string SendEmailNotification_ToRecipientNotFoundError {
            get {
                return ResourceManager.GetString("SendEmailNotification_ToRecipientNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the parent workflow..
        /// </summary>
        internal static string UnableToGetParentWorkflowError {
            get {
                return ResourceManager.GetString("UnableToGetParentWorkflowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to insert value of type &apos;{0}&apos; into workflow dictionary key &apos;{1}&apos; of type &apos;{2}&apos;..
        /// </summary>
        internal static string UpdateLookup_InsertVariableError {
            get {
                return ResourceManager.GetString("UpdateLookup_InsertVariableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request does not meet the conditions specified by the system administrator..
        /// </summary>
        internal static string VerifiyRequest_DenialRequestError {
            get {
                return ResourceManager.GetString("VerifiyRequest_DenialRequestError", resourceCulture);
            }
        }
    }
}
