//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicrosoftServices.IdentityManagement.WorkflowActivityLibrary.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ActivitySettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ActivitySettings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MicrosoftServices.IdentityManagement.WorkflowActivityLibrary.UI.ActivitySettings", typeof(ActivitySettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Display Name.
        /// </summary>
        internal static string ActivityDisplayName {
            get {
                return ResourceManager.GetString("ActivityDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An activity display name text box control has already been added to the controller.
        /// </summary>
        internal static string ActivityDisplayNameControlValidationError {
            get {
                return ResourceManager.GetString("ActivityDisplayNameControlValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Execution Condition.
        /// </summary>
        internal static string ActivityExecutionCondition {
            get {
                return ResourceManager.GetString("ActivityExecutionCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity execution condition must be a boolean function. Consider wrapping your current condition inside a ConvertToBoolean() function..
        /// </summary>
        internal static string ActivityExecutionConditionValidationError {
            get {
                return ResourceManager.GetString("ActivityExecutionConditionValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actor String.
        /// </summary>
        internal static string ActorString {
            get {
                return ResourceManager.GetString("ActorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actor Account Name.
        /// </summary>
        internal static string ActorTypeAccountName {
            get {
                return ResourceManager.GetString("ActorTypeAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the account name of the desired actor. The domain can optionally be specified using the Domain\AccountName syntax..
        /// </summary>
        internal static string ActorTypeAccountNameHelpText {
            get {
                return ResourceManager.GetString("ActorTypeAccountNameHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actor Expression.
        /// </summary>
        internal static string ActorTypeExpression {
            get {
                return ResourceManager.GetString("ActorTypeExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the lookup or expression which will resolve to the desired actor..
        /// </summary>
        internal static string ActorTypeExpressionHelpText {
            get {
                return ResourceManager.GetString("ActorTypeExpressionHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Delay.
        /// </summary>
        internal static string AddDelay {
            get {
                return ResourceManager.GetString("AddDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout Duration.
        /// </summary>
        internal static string AddDelayTimeoutDuration {
            get {
                return ResourceManager.GetString("AddDelayTimeoutDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a TimeSpan value or expression in &quot;hours:minutes:seconds&quot; format (e.g. &quot;00:30:00&quot; for 30 minutes).
        /// </summary>
        internal static string AddDelayTimeoutDurationHelpText {
            get {
                return ResourceManager.GetString("AddDelayTimeoutDurationHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Features.
        /// </summary>
        internal static string AdvancedFeatures {
            get {
                return ResourceManager.GetString("AdvancedFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select this option to configure advanced behavior for the activity..
        /// </summary>
        internal static string AdvancedFeaturesHelpText {
            get {
                return ResourceManager.GetString("AdvancedFeaturesHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Request Search Filter.
        /// </summary>
        internal static string AdvancedRequestSearchFilter {
            get {
                return ResourceManager.GetString("AdvancedRequestSearchFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optionally supply the resolvable XPath search filter which will return requests that should be evaluated as potential conflicts. If not supplied, the activity will evaluate all requests with a status of &apos;Authorizing&apos; and a matching target resource type and operation..
        /// </summary>
        internal static string AdvancedRequestSearchFilterHelpText {
            get {
                return ResourceManager.GetString("AdvancedRequestSearchFilterHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Authorization Policy.
        /// </summary>
        internal static string ApplyAuthorizationPolicy {
            get {
                return ResourceManager.GetString("ApplyAuthorizationPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity can be configured to apply authorization policy to child requests. Note: Authorization policy will disable publication of the create resource ID..
        /// </summary>
        internal static string ApplyAuthorizationPolicyHelpText {
            get {
                return ResourceManager.GetString("ApplyAuthorizationPolicyHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more attribute assignment definitions are incomplete.
        /// </summary>
        internal static string AttributeDefinitionValidationError {
            get {
                return ResourceManager.GetString("AttributeDefinitionValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Population.
        /// </summary>
        internal static string AttributesPopulation {
            get {
                return ResourceManager.GetString("AttributesPopulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify how attributes are to be populated on the new resource. Lookups are used in value expressions, but an attribute name must be specified as the target. Variables may also be specified as a target and then used in the value expression for subsequent definitions..
        /// </summary>
        internal static string AttributesPopulationHelpText {
            get {
                return ResourceManager.GetString("AttributesPopulationHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Expression.
        /// </summary>
        internal static string AttributesPopulationLeftHeader {
            get {
                return ResourceManager.GetString("AttributesPopulationLeftHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        internal static string AttributesPopulationRightHeader {
            get {
                return ResourceManager.GetString("AttributesPopulationRightHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Conflict.
        /// </summary>
        internal static string CheckForConflict {
            get {
                return ResourceManager.GetString("CheckForConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity can be configured to check for a conflict before creating the new resource..
        /// </summary>
        internal static string CheckForConflictHelpText {
            get {
                return ResourceManager.GetString("CheckForConflictHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more condition definitions are incomplete.
        /// </summary>
        internal static string ConditionDefinitionValidationError {
            get {
                return ResourceManager.GetString("ConditionDefinitionValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All conditions must resolve to a Boolean value.
        /// </summary>
        internal static string ConditionEvaluationValidationError {
            get {
                return ResourceManager.GetString("ConditionEvaluationValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optionally specify a condition which must be satisfied for execution of the activity&apos;s core task. This can be any WAL function expression resolving to a boolean value..
        /// </summary>
        internal static string ConditionHelpText {
            get {
                return ResourceManager.GetString("ConditionHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict Denial Message.
        /// </summary>
        internal static string ConflictDenialMessage {
            get {
                return ResourceManager.GetString("ConflictDenialMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply the resolvable denial message to be returned to the user when a conflicting resource is found..
        /// </summary>
        internal static string ConflictDenialMessageHelpText {
            get {
                return ResourceManager.GetString("ConflictDenialMessageHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict Filter.
        /// </summary>
        internal static string ConflictFilter {
            get {
                return ResourceManager.GetString("ConflictFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply the XPath filter which will identify conflicts for the generated value. The [//Value] lookup should be used in the filter to represent the value being evaluated for uniqueness. Example: /Person[AccountName = &apos;[//Value]&apos;]..
        /// </summary>
        internal static string ConflictFilterHelpText {
            get {
                return ResourceManager.GetString("ConflictFilterHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied conflict filter is invalid.
        /// </summary>
        internal static string ConflictFilterValidationError {
            get {
                return ResourceManager.GetString("ConflictFilterValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The conflict filter must contain the [//Value] lookup.
        /// </summary>
        internal static string ConflictFilterValueLookupValidationError {
            get {
                return ResourceManager.GetString("ConflictFilterValueLookupValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflicting Resource Search Filter.
        /// </summary>
        internal static string ConflictingResourceSearchFilter {
            get {
                return ResourceManager.GetString("ConflictingResourceSearchFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply the resolvable XPath search filter which will return any conflicting resource. Example: /Group[DisplayName = &apos;DL_Location_[//Target/OfficeLocation]&apos;].
        /// </summary>
        internal static string ConflictingResourceSearchFilterHelpText {
            get {
                return ResourceManager.GetString("ConflictingResourceSearchFilterHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply the resolvable XPath search filter which will return any conflicting resource. Example: /Person[EmployeeID = &apos;[//Effective/EmployeeID]&apos;].
        /// </summary>
        internal static string ConflictingResourceSearchFilterHelpText2 {
            get {
                return ResourceManager.GetString("ConflictingResourceSearchFilterHelpText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied conflicting resource search filter is invalid.
        /// </summary>
        internal static string ConflictResourceSearchFilterValidationError {
            get {
                return ResourceManager.GetString("ConflictResourceSearchFilterValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Resource.
        /// </summary>
        internal static string CreateResource {
            get {
                return ResourceManager.GetString("CreateResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The definitions table is corrupt..
        /// </summary>
        internal static string DefinitionsConverter_NullOrEmptyDefinitionsTableError {
            get {
                return ResourceManager.GetString("DefinitionsConverter_NullOrEmptyDefinitionsTableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Resources.
        /// </summary>
        internal static string DeleteResources {
            get {
                return ResourceManager.GetString("DeleteResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail on Conflict.
        /// </summary>
        internal static string FailOnConflict {
            get {
                return ResourceManager.GetString("FailOnConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify whether or not the activity should generate an error when a conflict is identified..
        /// </summary>
        internal static string FailOnConflictHelpText {
            get {
                return ResourceManager.GetString("FailOnConflictHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail When Script is Missing.
        /// </summary>
        internal static string FailOnMissingScript {
            get {
                return ResourceManager.GetString("FailOnMissingScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify whether or not the activity should generate an error when the script lookup resolves to a null value..
        /// </summary>
        internal static string FailOnMissingScriptHelpText {
            get {
                return ResourceManager.GetString("FailOnMissingScriptHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The control must be initialized before it can be added to the form controller.
        /// </summary>
        internal static string FormControlInitializationError {
            get {
                return ResourceManager.GetString("FormControlInitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Unique Value.
        /// </summary>
        internal static string GenerateUniqueValue {
            get {
                return ResourceManager.GetString("GenerateUniqueValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid Guid must be supplied for {0}.
        /// </summary>
        internal static string GuidFieldValidationError {
            get {
                return ResourceManager.GetString("GuidFieldValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impersonate PowerShell user.
        /// </summary>
        internal static string ImpersonatePowerShellUser {
            get {
                return ResourceManager.GetString("ImpersonatePowerShellUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impersonate the specified PowerShell user while running the PowerShell script..
        /// </summary>
        internal static string ImpersonatePowerShellUserHelpText {
            get {
                return ResourceManager.GetString("ImpersonatePowerShellUserHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log on type.
        /// </summary>
        internal static string ImpersonationLogOnType {
            get {
                return ResourceManager.GetString("ImpersonationLogOnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log on type to use when impersonating the PowerShell user..
        /// </summary>
        internal static string ImpersonationLogonTypeHelpText {
            get {
                return ResourceManager.GetString("ImpersonationLogonTypeHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log on as a batch job.
        /// </summary>
        internal static string ImpersonationLogOnTypeLogOnBatch {
            get {
                return ResourceManager.GetString("ImpersonationLogOnTypeLogOnBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactive log on.
        /// </summary>
        internal static string ImpersonationLogOnTypeLogOnInteractive {
            get {
                return ResourceManager.GetString("ImpersonationLogOnTypeLogOnInteractive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network log on.
        /// </summary>
        internal static string ImpersonationLogOnTypeLogOnNetwork {
            get {
                return ResourceManager.GetString("ImpersonationLogOnTypeLogOnNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network log on with plain text.
        /// </summary>
        internal static string ImpersonationLogOnTypeLogOnNetworkClearText {
            get {
                return ResourceManager.GetString("ImpersonationLogOnTypeLogOnNetworkClearText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log on as a service.
        /// </summary>
        internal static string ImpersonationLogOnTypeLogOnService {
            get {
                return ResourceManager.GetString("ImpersonationLogOnTypeLogOnService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied value could not be matched to a value for the ActorType enumeration.
        /// </summary>
        internal static string InvalidActorType {
            get {
                return ResourceManager.GetString("InvalidActorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied value could not be matched to a value for the LogOnType enumeration..
        /// </summary>
        internal static string InvalidLogOnType {
            get {
                return ResourceManager.GetString("InvalidLogOnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied value could not be matched to a value for the PowerShellInputType enumeration.
        /// </summary>
        internal static string InvalidPowerShellInputType {
            get {
                return ResourceManager.GetString("InvalidPowerShellInputType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied value could not be matched to a value for the PowerShellReturnType enumeration.
        /// </summary>
        internal static string InvalidPowerShellReturnType {
            get {
                return ResourceManager.GetString("InvalidPowerShellReturnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied value could not be matched to a value for the PowerShellScriptLocation enumeration.
        /// </summary>
        internal static string InvalidPowerShellScriptLocation {
            get {
                return ResourceManager.GetString("InvalidPowerShellScriptLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iteration.
        /// </summary>
        internal static string Iteration {
            get {
                return ResourceManager.GetString("Iteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optionally configure the activity to iterate through a collection of values by specifying a lookup or expression. The instance value can be referenced in update definitions using lookups with the [//Value/…] grammar. Note: Iteration will disable publication of created and conflicting resource IDs..
        /// </summary>
        internal static string IterationHelpText {
            get {
                return ResourceManager.GetString("IterationHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity is not configured for iteration. Expressions using the [//Value/...] syntax cannot be used..
        /// </summary>
        internal static string IterationValidationError {
            get {
                return ResourceManager.GetString("IterationValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDAP Queries.
        /// </summary>
        internal static string LdapQueries {
            get {
                return ResourceManager.GetString("LdapQueries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify one or more LDAP queries which should be run by the activity to identify conflicts. The [//Value] lookup should be used in each LDAP filter to represent the value being evaluated for uniqueness. All queries will be executed under the context of the FIM Service account..
        /// </summary>
        internal static string LdapQueriesHelpText {
            get {
                return ResourceManager.GetString("LdapQueriesHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Entry Path.
        /// </summary>
        internal static string LdapQueriesLeftHeader {
            get {
                return ResourceManager.GetString("LdapQueriesLeftHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDAP Filter.
        /// </summary>
        internal static string LdapQueriesRightHeader {
            get {
                return ResourceManager.GetString("LdapQueriesRightHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more LDAP query definitions are incomplete.
        /// </summary>
        internal static string LdapQueryDefinitionValidationError {
            get {
                return ResourceManager.GetString("LdapQueryDefinitionValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All LDAP filters must contain the [//Value] lookup.
        /// </summary>
        internal static string LdapQueryDefinitionValueLookupValidationError {
            get {
                return ResourceManager.GetString("LdapQueryDefinitionValueLookupValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string LinkButtonAdd {
            get {
                return ResourceManager.GetString("LinkButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string LinkButtonDelete {
            get {
                return ResourceManager.GetString("LinkButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        internal static string LinkButtonMoveDown {
            get {
                return ResourceManager.GetString("LinkButtonMoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        internal static string LinkButtonMoveUp {
            get {
                return ResourceManager.GetString("LinkButtonMoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load user profile.
        /// </summary>
        internal static string LoadUserProfile {
            get {
                return ResourceManager.GetString("LoadUserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load user profile when impersonating the PowerShell user..
        /// </summary>
        internal static string LoadUserProfileHelpText {
            get {
                return ResourceManager.GetString("LoadUserProfileHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Named Parameters.
        /// </summary>
        internal static string NamedParameters {
            get {
                return ResourceManager.GetString("NamedParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify one or more named parameters to be supplied to the script upon execution. Value expressions may include functions, lookups, and concatenation..
        /// </summary>
        internal static string NamedParametersHelpText {
            get {
                return ResourceManager.GetString("NamedParametersHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        internal static string NamedParametersLeftHeader {
            get {
                return ResourceManager.GetString("NamedParametersLeftHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Expression.
        /// </summary>
        internal static string NamedParametersRightHeader {
            get {
                return ResourceManager.GetString("NamedParametersRightHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of definition listings is null.
        /// </summary>
        internal static string NullDefinitionListingsError {
            get {
                return ResourceManager.GetString("NullDefinitionListingsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid integer must be supplied for {0}.
        /// </summary>
        internal static string NumericFieldValidationError {
            get {
                return ResourceManager.GetString("NumericFieldValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify UserName and Password of the impersonated user..
        /// </summary>
        internal static string PowerShellImpersonationSettingsValidationError {
            get {
                return ResourceManager.GetString("PowerShellImpersonationSettingsValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments.
        /// </summary>
        internal static string PowerShellInputTypeArguments {
            get {
                return ResourceManager.GetString("PowerShellInputTypeArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Named Parameters.
        /// </summary>
        internal static string PowerShellInputTypeNamedParameters {
            get {
                return ResourceManager.GetString("PowerShellInputTypeNamedParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string PowerShellInputTypeNone {
            get {
                return ResourceManager.GetString("PowerShellInputTypeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string PowerShellReturnTypeNone {
            get {
                return ResourceManager.GetString("PowerShellReturnTypeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Value.
        /// </summary>
        internal static string PowerShellReturnTypeSingleValue {
            get {
                return ResourceManager.GetString("PowerShellReturnTypeSingleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table of Values.
        /// </summary>
        internal static string PowerShellReturnTypeTable {
            get {
                return ResourceManager.GetString("PowerShellReturnTypeTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script.
        /// </summary>
        internal static string PowerShellScript {
            get {
                return ResourceManager.GetString("PowerShellScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply the PowerShell script that will be executed by the activity. The script will be stored in the workflow definition as an activity configuration property..
        /// </summary>
        internal static string PowerShellScriptHelpText {
            get {
                return ResourceManager.GetString("PowerShellScriptHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Type.
        /// </summary>
        internal static string PowerShellScriptInputType {
            get {
                return ResourceManager.GetString("PowerShellScriptInputType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If input is required, specify how it should be provided to the PowerShell script..
        /// </summary>
        internal static string PowerShellScriptInputTypeHelpText {
            get {
                return ResourceManager.GetString("PowerShellScriptInputTypeHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Location.
        /// </summary>
        internal static string PowerShellScriptLocation {
            get {
                return ResourceManager.GetString("PowerShellScriptLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify how the activity will locate the script for execution..
        /// </summary>
        internal static string PowerShellScriptLocationHelpText {
            get {
                return ResourceManager.GetString("PowerShellScriptLocationHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Lookup.
        /// </summary>
        internal static string PowerShellScriptLookup {
            get {
                return ResourceManager.GetString("PowerShellScriptLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the lookup which represents the script to be executed by the activity..
        /// </summary>
        internal static string PowerShellScriptLookupHelpText {
            get {
                return ResourceManager.GetString("PowerShellScriptLookupHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Path.
        /// </summary>
        internal static string PowerShellScriptPath {
            get {
                return ResourceManager.GetString("PowerShellScriptPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the full path to the PowerShell script file. This path must be accessible from all instances of the FIM Service..
        /// </summary>
        internal static string PowerShellScriptPathHelpText {
            get {
                return ResourceManager.GetString("PowerShellScriptPathHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerShell Script User.
        /// </summary>
        internal static string PowerShellUser {
            get {
                return ResourceManager.GetString("PowerShellUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PowerShell user must be specified in the domain\userName or UPN format when Impersonate PowerShell User option is selected..
        /// </summary>
        internal static string PowerShellUserFormatValidationError {
            get {
                return ResourceManager.GetString("PowerShellUserFormatValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the user to be used to construct PowerShell Credential object. When impersonating, the user name must be in the domain\userName or UPN format..
        /// </summary>
        internal static string PowerShellUserHelpText {
            get {
                return ResourceManager.GetString("PowerShellUserHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerShell Script User Password.
        /// </summary>
        internal static string PowerShellUserPassword {
            get {
                return ResourceManager.GetString("PowerShellUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the password to be used to construct PowerShell Credential object. The expected format is: [base64EncodedEncryptedData] | [app:\appSettings\[key],[LocalMachine|CurrentUser]] | [cert:\[LocalMachine|CurrentUser]\my\[thumbprint],base64EncodedEncryptedData]].
        /// </summary>
        internal static string PowerShellUserPasswordHelpText {
            get {
                return ResourceManager.GetString("PowerShellUserPasswordHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the PowerShell user password..
        /// </summary>
        internal static string PowerShellUserPasswordValidationError {
            get {
                return ResourceManager.GetString("PowerShellUserPasswordValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queries.
        /// </summary>
        internal static string Queries {
            get {
                return ResourceManager.GetString("Queries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify one or more XPath queries which should be run by the activity. Queries can be referenced in expressions using lookups with the [//Queries/Key/...] grammar..
        /// </summary>
        internal static string QueriesHelpText {
            get {
                return ResourceManager.GetString("QueriesHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string QueriesLeftHeader {
            get {
                return ResourceManager.GetString("QueriesLeftHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XPath Filter.
        /// </summary>
        internal static string QueriesRightHeader {
            get {
                return ResourceManager.GetString("QueriesRightHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more query definitions are incomplete.
        /// </summary>
        internal static string QueryDefinitionValidationError {
            get {
                return ResourceManager.GetString("QueryDefinitionValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query key &apos;{0}&apos; is invalid.
        /// </summary>
        internal static string QueryDefintionLeftValidationError {
            get {
                return ResourceManager.GetString("QueryDefintionLeftValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XPath filter supplied for key &apos;{0}&apos; is invalid.
        /// </summary>
        internal static string QueryDefintionRightValidationError {
            get {
                return ResourceManager.GetString("QueryDefintionRightValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query LDAP for Conflicts.
        /// </summary>
        internal static string QueryLdapForConflicts {
            get {
                return ResourceManager.GetString("QueryLdapForConflicts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity can be configured to query one or more LDAP directories to identify conflicts for the generated value..
        /// </summary>
        internal static string QueryLdapForConflictsHelpText {
            get {
                return ResourceManager.GetString("QueryLdapForConflictsHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Resources.
        /// </summary>
        internal static string QueryResources {
            get {
                return ResourceManager.GetString("QueryResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity can be configured to query resources which can be used in update definitions..
        /// </summary>
        internal static string QueryResourcesHelpText {
            get {
                return ResourceManager.GetString("QueryResourcesHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity is not configured to query resources. Expressions using the [//Query/Key/...] syntax cannot be used..
        /// </summary>
        internal static string QueryResourcesValidationError {
            get {
                return ResourceManager.GetString("QueryResourcesValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Actor.
        /// </summary>
        internal static string RequestActor {
            get {
                return ResourceManager.GetString("RequestActor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization Policy cannot be applied when Request Actor is Service Account.
        /// </summary>
        internal static string RequestActorValidationError {
            get {
                return ResourceManager.GetString("RequestActorValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Approval.
        /// </summary>
        internal static string RequestApproval {
            get {
                return ResourceManager.GetString("RequestApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approvers.
        /// </summary>
        internal static string RequestApprovalApprovers {
            get {
                return ResourceManager.GetString("RequestApprovalApprovers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a valid email address..
        /// </summary>
        internal static string RequestApprovalApproversFieldValidationError {
            get {
                return ResourceManager.GetString("RequestApprovalApproversFieldValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User and groups who can approve this request. Specify a search filter, a lookup expression or a &apos;;&apos; delimited list of email addresses..
        /// </summary>
        internal static string RequestApprovalApproversHelpText {
            get {
                return ResourceManager.GetString("RequestApprovalApproversHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Approval Email Template.
        /// </summary>
        internal static string RequestApprovalCompleteEmailTemplate {
            get {
                return ResourceManager.GetString("RequestApprovalCompleteEmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is sent to approvers. Specify a search filter or a lookup expression..
        /// </summary>
        internal static string RequestApprovalCompleteEmailTemplateHelpText {
            get {
                return ResourceManager.GetString("RequestApprovalCompleteEmailTemplateHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected Request Email Template.
        /// </summary>
        internal static string RequestApprovalDeniedEmailTemplate {
            get {
                return ResourceManager.GetString("RequestApprovalDeniedEmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is sent to requestor. Specify a search filter or a lookup expression..
        /// </summary>
        internal static string RequestApprovalDeniedEmailTemplateHelpText {
            get {
                return ResourceManager.GetString("RequestApprovalDeniedEmailTemplateHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration..
        /// </summary>
        internal static string RequestApprovalDuration {
            get {
                return ResourceManager.GetString("RequestApprovalDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a lookup expression or a number for the approval duration..
        /// </summary>
        internal static string RequestApprovalDurationFieldValidationError {
            get {
                return ResourceManager.GetString("RequestApprovalDurationFieldValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of days before escalation and time out. Specify a lookup expression or a number..
        /// </summary>
        internal static string RequestApprovalDurationHelpText {
            get {
                return ResourceManager.GetString("RequestApprovalDurationHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Approval Email Template.
        /// </summary>
        internal static string RequestApprovalEmailTemplate {
            get {
                return ResourceManager.GetString("RequestApprovalEmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is sent to approvers. Specify a search filter or a lookup expression..
        /// </summary>
        internal static string RequestApprovalEmailTemplateHelpText {
            get {
                return ResourceManager.GetString("RequestApprovalEmailTemplateHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the supplied Email Template value is not an XPath filter or a lookup expression, it must be a valid GUID value..
        /// </summary>
        internal static string RequestApprovalEmailTemplateValidationError {
            get {
                return ResourceManager.GetString("RequestApprovalEmailTemplateValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escalated Approvers.
        /// </summary>
        internal static string RequestApprovalEscalation {
            get {
                return ResourceManager.GetString("RequestApprovalEscalation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Approval Escalation Email Template.
        /// </summary>
        internal static string RequestApprovalEscalationEmailTemplate {
            get {
                return ResourceManager.GetString("RequestApprovalEscalationEmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escalation email template is required when escalated approvers are specified..
        /// </summary>
        internal static string RequestApprovalEscalationEmailTemplateFieldValidationError {
            get {
                return ResourceManager.GetString("RequestApprovalEscalationEmailTemplateFieldValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is sent to escalated approvers. Specify a search filter or a lookup expression..
        /// </summary>
        internal static string RequestApprovalEscalationEmailTemplateHelpText {
            get {
                return ResourceManager.GetString("RequestApprovalEscalationEmailTemplateHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User and groups who can approve this request after it has been escalated. Specify a search filter, a lookup expression or a &apos;;&apos; delimited list of email addresses..
        /// </summary>
        internal static string RequestApprovalEscalationHelpText {
            get {
                return ResourceManager.GetString("RequestApprovalEscalationHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Threshold.
        /// </summary>
        internal static string RequestApprovalThreshold {
            get {
                return ResourceManager.GetString("RequestApprovalThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold field must be a lookup expression or a number..
        /// </summary>
        internal static string RequestApprovalThresholdFieldValidationError {
            get {
                return ResourceManager.GetString("RequestApprovalThresholdFieldValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of approvers required. Specify a lookup expression or a number..
        /// </summary>
        internal static string RequestApprovalThresholdHelpText {
            get {
                return ResourceManager.GetString("RequestApprovalThresholdHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timed out Request Email Template.
        /// </summary>
        internal static string RequestApprovalTimeoutEmailTemplate {
            get {
                return ResourceManager.GetString("RequestApprovalTimeoutEmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is sent to requestor. Specify a search filter or a lookup expression..
        /// </summary>
        internal static string RequestApprovalTimeoutEmailTemplateHelpText {
            get {
                return ResourceManager.GetString("RequestApprovalTimeoutEmailTemplateHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflicting Request Denial Message.
        /// </summary>
        internal static string RequestConflictDenialMessage {
            get {
                return ResourceManager.GetString("RequestConflictDenialMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply the resolvable denial message to be returned to the user when a conflicting request is found..
        /// </summary>
        internal static string RequestConflictDenialMessageHelpText {
            get {
                return ResourceManager.GetString("RequestConflictDenialMessageHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Condition Identifying a Conflicting Request.
        /// </summary>
        internal static string RequestConflictMatchCondition {
            get {
                return ResourceManager.GetString("RequestConflictMatchCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply the Boolean condition which identifies an evaluated request as a conflict. Example: And(Eq([//Delta/AccountName], [//ComparedRequest/Delta/AccountName]), Eq([//Delta/Domain], [//ComparedRequest/Delta/Domain])).
        /// </summary>
        internal static string RequestConflictMatchConditionHelpText {
            get {
                return ResourceManager.GetString("RequestConflictMatchConditionHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requestor.
        /// </summary>
        internal static string Requestor {
            get {
                return ResourceManager.GetString("Requestor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value must be supplied for {0}.
        /// </summary>
        internal static string RequiredFieldValidationError {
            get {
                return ResourceManager.GetString("RequiredFieldValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string RequiredIndicator {
            get {
                return ResourceManager.GetString("RequiredIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Request Conditions.
        /// </summary>
        internal static string RequiredRequestConditions {
            get {
                return ResourceManager.GetString("RequiredRequestConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the conditions which must be satisfied for the request to be considered valid. The activity supports the specification of function-based conditions which reference resolvable expressions. If any condition does not evaluate to true, the request will be denied with the associated error message..
        /// </summary>
        internal static string RequiredRequestConditionsHelpText {
            get {
                return ResourceManager.GetString("RequiredRequestConditionsHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Condition for the Request.
        /// </summary>
        internal static string RequiredRequestConditionsLeftHeader {
            get {
                return ResourceManager.GetString("RequiredRequestConditionsLeftHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denial Message if Condition is not Satisfied.
        /// </summary>
        internal static string RequiredRequestConditionsRightHeader {
            get {
                return ResourceManager.GetString("RequiredRequestConditionsRightHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolve Dynamic Grammar.
        /// </summary>
        internal static string ResolveDynamicGrammar {
            get {
                return ResourceManager.GetString("ResolveDynamicGrammar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity can be configured to resolve / evaluate lookups and expressions in the values returned by the expressions in update definitions. Example: The string returned by [//Queries/EmailTemplate/EmailBody] will be parsed and all lookups will be resolved..
        /// </summary>
        internal static string ResolveDynamicGrammarHelpText {
            get {
                return ResourceManager.GetString("ResolveDynamicGrammarHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolve From Expression.
        /// </summary>
        internal static string ResolveFromExpression {
            get {
                return ResourceManager.GetString("ResolveFromExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolve Target(s).
        /// </summary>
        internal static string ResolveTargets {
            get {
                return ResourceManager.GetString("ResolveTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Type.
        /// </summary>
        internal static string ResourceType {
            get {
                return ResourceManager.GetString("ResourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the type of resource to be created by the activity..
        /// </summary>
        internal static string ResourceTypeHelpText {
            get {
                return ResourceManager.GetString("ResourceTypeHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource type &apos;{0}&apos; is invalid.
        /// </summary>
        internal static string ResourceTypeValidationError {
            get {
                return ResourceManager.GetString("ResourceTypeValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run PowerShell Script.
        /// </summary>
        internal static string RunPowerShellScript {
            get {
                return ResourceManager.GetString("RunPowerShellScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments.
        /// </summary>
        internal static string ScriptArguments {
            get {
                return ResourceManager.GetString("ScriptArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify one or more arguments to be supplied to the script upon execution. Arguments will be provided, without parameter names, in the order in which they are listed. Value expressions may include functions, lookups, and concatenation..
        /// </summary>
        internal static string ScriptArgumentsHelpText {
            get {
                return ResourceManager.GetString("ScriptArgumentsHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Expression.
        /// </summary>
        internal static string ScriptArgumentsLeftHeader {
            get {
                return ResourceManager.GetString("ScriptArgumentsLeftHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more arguments are incomplete.
        /// </summary>
        internal static string ScriptArgumentValidationError {
            get {
                return ResourceManager.GetString("ScriptArgumentValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read from File.
        /// </summary>
        internal static string ScriptLocationDisk {
            get {
                return ResourceManager.GetString("ScriptLocationDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolve from Lookup.
        /// </summary>
        internal static string ScriptLocationResolveLookup {
            get {
                return ResourceManager.GetString("ScriptLocationResolveLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include in Workflow Definition.
        /// </summary>
        internal static string ScriptLocationWorkflowDefinition {
            get {
                return ResourceManager.GetString("ScriptLocationWorkflowDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more parameter definitions are incomplete.
        /// </summary>
        internal static string ScriptParameterDefintionValidationError {
            get {
                return ResourceManager.GetString("ScriptParameterDefintionValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Return Type.
        /// </summary>
        internal static string ScriptReturnType {
            get {
                return ResourceManager.GetString("ScriptReturnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity can capture a return value from the PowerShell script and publish it to a lookup. Alternatively, the PowerShell script may return a table of named values which can be published to the workflow dictionary using corresponding key names..
        /// </summary>
        internal static string ScriptReturnTypeHelpText {
            get {
                return ResourceManager.GetString("ScriptReturnTypeHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Value Lookup.
        /// </summary>
        internal static string ScriptReturnValueLookup {
            get {
                return ResourceManager.GetString("ScriptReturnValueLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the lookup to which the return value should be published..
        /// </summary>
        internal static string ScriptReturnValueLookupHelpText {
            get {
                return ResourceManager.GetString("ScriptReturnValueLookupHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Account Name.
        /// </summary>
        internal static string SearchByAccountName {
            get {
                return ResourceManager.GetString("SearchByAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for Target(s).
        /// </summary>
        internal static string SearchForTargets {
            get {
                return ResourceManager.GetString("SearchForTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Email Notification.
        /// </summary>
        internal static string SendEmailNotification {
            get {
                return ResourceManager.GetString("SendEmailNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Bcc&apos; recipients.
        /// </summary>
        internal static string SendEmailNotificationBcc {
            get {
                return ResourceManager.GetString("SendEmailNotificationBcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a search filter, a lookup expression or a &apos;;&apos; delimited list of email addresses..
        /// </summary>
        internal static string SendEmailNotificationBccHelpText {
            get {
                return ResourceManager.GetString("SendEmailNotificationBccHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;CC&apos; recipients.
        /// </summary>
        internal static string SendEmailNotificationCC {
            get {
                return ResourceManager.GetString("SendEmailNotificationCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a search filter, a lookup expression or a &apos;;&apos; delimited list of email addresses..
        /// </summary>
        internal static string SendEmailNotificationCCHelpText {
            get {
                return ResourceManager.GetString("SendEmailNotificationCCHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Template.
        /// </summary>
        internal static string SendEmailNotificationEmailTemplate {
            get {
                return ResourceManager.GetString("SendEmailNotificationEmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify an XPath to an EmailTemplate resource or a lookup expression resolving to an EmailTemplate resource..
        /// </summary>
        internal static string SendEmailNotificationEmailTemplateHelpText {
            get {
                return ResourceManager.GetString("SendEmailNotificationEmailTemplateHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the supplied Email Template value is not an XPath filter or a lookup expression, it must be a valid GUID value..
        /// </summary>
        internal static string SendEmailNotificationEmailTemplateValidationError {
            get {
                return ResourceManager.GetString("SendEmailNotificationEmailTemplateValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;To&apos; recipients must be specified..
        /// </summary>
        internal static string SendEmailNotificationRecipientFieldValidationError {
            get {
                return ResourceManager.GetString("SendEmailNotificationRecipientFieldValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a valid email address..
        /// </summary>
        internal static string SendEmailNotificationRecipientFieldValidationError2 {
            get {
                return ResourceManager.GetString("SendEmailNotificationRecipientFieldValidationError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppress Exception.
        /// </summary>
        internal static string SendEmailNotificationSuppressException {
            get {
                return ResourceManager.GetString("SendEmailNotificationSuppressException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppresses notification failure from the EmailNotification Activity..
        /// </summary>
        internal static string SendEmailNotificationSuppressExceptionHelpText {
            get {
                return ResourceManager.GetString("SendEmailNotificationSuppressExceptionHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;To&apos; recipients.
        /// </summary>
        internal static string SendEmailNotificationTo {
            get {
                return ResourceManager.GetString("SendEmailNotificationTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a search filter, a lookup expression or a &apos;;&apos; delimited list of email addresses..
        /// </summary>
        internal static string SendEmailNotificationToHelpText {
            get {
                return ResourceManager.GetString("SendEmailNotificationToHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Account.
        /// </summary>
        internal static string ServiceAccount {
            get {
                return ResourceManager.GetString("ServiceAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Expression.
        /// </summary>
        internal static string TargetExpression {
            get {
                return ResourceManager.GetString("TargetExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target for Conflicting Resource ID.
        /// </summary>
        internal static string TargetForConflictingResourceID {
            get {
                return ResourceManager.GetString("TargetForConflictingResourceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity can be configured to publish the ID of the identified conflicting resource to an attribute or workflow dictionary key. The target must be expressed as a lookup..
        /// </summary>
        internal static string TargetForConflictingResourceIDHelpText {
            get {
                return ResourceManager.GetString("TargetForConflictingResourceIDHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target for Created Resource ID.
        /// </summary>
        internal static string TargetForCreatedResourceID {
            get {
                return ResourceManager.GetString("TargetForCreatedResourceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity can be configured to publish the ID of the new resource to an attribute or workflow dictionary key after creation. The target must be expressed as a lookup..
        /// </summary>
        internal static string TargetForCreatedResourceIDHelpText {
            get {
                return ResourceManager.GetString("TargetForCreatedResourceIDHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target for Deletion.
        /// </summary>
        internal static string TargetForDeletion {
            get {
                return ResourceManager.GetString("TargetForDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify how the activity will identify the target(s) for deletion..
        /// </summary>
        internal static string TargetForDeletionHelpText {
            get {
                return ResourceManager.GetString("TargetForDeletionHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target for Generated Value.
        /// </summary>
        internal static string TargetForGeneratedValue {
            get {
                return ResourceManager.GetString("TargetForGeneratedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the attribute or workflow dictionary key to which the generated value should be published. The target must be expressed as a lookup..
        /// </summary>
        internal static string TargetForGeneratedValueHelpText {
            get {
                return ResourceManager.GetString("TargetForGeneratedValueHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Lookup.
        /// </summary>
        internal static string TargetLookup {
            get {
                return ResourceManager.GetString("TargetLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Target Lookup must be supplied..
        /// </summary>
        internal static string TargetLookupExpressionMissingValidationError {
            get {
                return ResourceManager.GetString("TargetLookupExpressionMissingValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply the lookup which will identify the target(s) for deletion. Example: [//Target/OwnedAccounts].
        /// </summary>
        internal static string TargetLookupHelpText {
            get {
                return ResourceManager.GetString("TargetLookupHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid target lookup.
        /// </summary>
        internal static string TargetLookupValidationError {
            get {
                return ResourceManager.GetString("TargetLookupValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Search Filter.
        /// </summary>
        internal static string TargetSearchFilter {
            get {
                return ResourceManager.GetString("TargetSearchFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply the resolvable XPath search filter which will return the target(s) for deletion. Example: /Account[AccountOwner = &apos;[//Target/ObjectID]&apos;].
        /// </summary>
        internal static string TargetSearchFilterHelpText {
            get {
                return ResourceManager.GetString("TargetSearchFilterHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target &apos;{0}&apos; is invalid.
        /// </summary>
        internal static string TargetValidationError {
            get {
                return ResourceManager.GetString("TargetValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Search Target XPath must be supplied..
        /// </summary>
        internal static string TargetXPathExpressionMissingValidationError {
            get {
                return ResourceManager.GetString("TargetXPathExpressionMissingValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniqueness Key Seed.
        /// </summary>
        internal static string UniquenessKeySeed {
            get {
                return ResourceManager.GetString("UniquenessKeySeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the first number which should be included in the value when all other expressions result in a conflict..
        /// </summary>
        internal static string UniquenessKeySeedHelpText {
            get {
                return ResourceManager.GetString("UniquenessKeySeedHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an unnamed field.
        /// </summary>
        internal static string UnnamedField {
            get {
                return ResourceManager.GetString("UnnamedField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more update definitions are incomplete.
        /// </summary>
        internal static string UpdateDefinitionValidationError {
            get {
                return ResourceManager.GetString("UpdateDefinitionValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Resources.
        /// </summary>
        internal static string UpdateResources {
            get {
                return ResourceManager.GetString("UpdateResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        internal static string Updates {
            get {
                return ResourceManager.GetString("Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Null.
        /// </summary>
        internal static string UpdatesCheckHeader {
            get {
                return ResourceManager.GetString("UpdatesCheckHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the updates to be performed by the activity. Lookups are used in value expressions and are also used to represent target resources and attributes. Variables may also be specified as a target and then used in the value expression for subsequent update definitions. The &quot;Allow Null&quot; option enforces the deletion of target values when the source resolves to null..
        /// </summary>
        internal static string UpdatesHelpText {
            get {
                return ResourceManager.GetString("UpdatesHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Expression.
        /// </summary>
        internal static string UpdatesLeftHeader {
            get {
                return ResourceManager.GetString("UpdatesLeftHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        internal static string UpdatesRightHeader {
            get {
                return ResourceManager.GetString("UpdatesRightHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Workflow Target.
        /// </summary>
        internal static string UseWorkflowTarget {
            get {
                return ResourceManager.GetString("UseWorkflowTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last value expression in the list must contain the [//UniquenessKey] lookup..
        /// </summary>
        internal static string ValueExpressionMissingUniquenessKeyValidationError {
            get {
                return ResourceManager.GetString("ValueExpressionMissingUniquenessKeyValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Expressions.
        /// </summary>
        internal static string ValueExpressions {
            get {
                return ResourceManager.GetString("ValueExpressions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply the expressions which will be used to generate the unique value. The first expression which results in a unique value will be used. The last expression in the list must contain the [//UniquenessKey] lookup to ensure a unique value can be generated. As a last resort, this lookup will be replaced with an integer which will be incremented until a unique value is identified..
        /// </summary>
        internal static string ValueExpressionsHelpText {
            get {
                return ResourceManager.GetString("ValueExpressionsHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Expression.
        /// </summary>
        internal static string ValueExpressionsLeftHeader {
            get {
                return ResourceManager.GetString("ValueExpressionsLeftHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the last value expression in the list can leverage the [//UniquenessKey] lookup..
        /// </summary>
        internal static string ValueExpressionUniquenessKeyValidationError {
            get {
                return ResourceManager.GetString("ValueExpressionUniquenessKeyValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more value expressions are incomplete..
        /// </summary>
        internal static string ValueExpressionValidationError {
            get {
                return ResourceManager.GetString("ValueExpressionValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Request.
        /// </summary>
        internal static string VerifyRequest {
            get {
                return ResourceManager.GetString("VerifyRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify the Request as Unique.
        /// </summary>
        internal static string VerifyRequestUniqueness {
            get {
                return ResourceManager.GetString("VerifyRequestUniqueness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify whether or not a uniqueness validation should be performed for the request against other authorizing requests..
        /// </summary>
        internal static string VerifyRequestUniquenessHelpText {
            get {
                return ResourceManager.GetString("VerifyRequestUniquenessHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify the Resource as Unique.
        /// </summary>
        internal static string VerifyResourceUniqueness {
            get {
                return ResourceManager.GetString("VerifyResourceUniqueness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify whether or not a uniqueness validation should be performed for the target resource..
        /// </summary>
        internal static string VerifyResourceUniquenessHelpText {
            get {
                return ResourceManager.GetString("VerifyResourceUniquenessHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Lookup Variables.
        /// </summary>
        internal static string WorkflowDataVariables {
            get {
                return ResourceManager.GetString("WorkflowDataVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more workflow lookup variable definitions are incomplete.
        /// </summary>
        internal static string WorkflowDataVariablesDefinitionValidationError {
            get {
                return ResourceManager.GetString("WorkflowDataVariablesDefinitionValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the Workflow Lookup Variables to be used in the email template..
        /// </summary>
        internal static string WorkflowDataVariablesHelpText {
            get {
                return ResourceManager.GetString("WorkflowDataVariablesHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Expression.
        /// </summary>
        internal static string WorkflowDataVariablesLeftHeader {
            get {
                return ResourceManager.GetString("WorkflowDataVariablesLeftHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        internal static string WorkflowDataVariablesRightHeader {
            get {
                return ResourceManager.GetString("WorkflowDataVariablesRightHeader", resourceCulture);
            }
        }
    }
}
